[package]
name = "beefy-light-client-primitives"
version = "0.1.0"
edition = "2021"
authors = ["Seun Lanlege <seunlanlege@gmail.com>", "David Salami <wizdave97@gmail.com>"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
beefy-primitives = { package = "sp-consensus-beefy", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
rs_merkle = { version = "1.2.0", default-features = false }
mmr-lib= { package = "ckb-merkle-mountain-range", version = "0.3.2", default-features = false }
pallet-mmr-primitives = { package = "sp-mmr-primitives", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
derive_more = { version = "0.99.17", default-features = false, features = ["from"]  }
light-client-common = { path = "../../../light-clients/common", default-features = false }
serde = { version = "1.0.144", features = ["derive"], optional = true }
[features]
default = ["std"]
std = [
	"sp-std/std",
	"sp-core/std",
	"beefy-primitives/std",
	"codec/std",
	"rs_merkle/std",
	"mmr-lib/std",
	"pallet-mmr-primitives/std",
	"light-client-common/std",
	"serde",
	"serde/std"
]
