[package]
name = "hyperspace-parachain"
version = "0.1.0"
edition = "2021"
description = "Hyperspace relayer interface for Parachains"
authors = [
	"Seun Lanlege <seunlanlege@gmail.com>",
	"David Salami <wizdave97@gmail.com>",
]

[dependencies]
primitives = { path = "../primitives", package = "hyperspace-primitives", features = [
	"testing",
] }

# crates.io
anyhow = "1.0.65"
futures = "0.3.21"
async-trait = "0.1.53"
log = "0.4.17"
hex = "0.4.3"
tokio = { version = "1.32.0", features = ["macros", "sync"] }
rs_merkle = "1.2.0"
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
	"max-encoded-len",
] }
hex-literal = "0.3.4"
serde_json = "1.0.74"
derive_more = { version = "0.99", features = ["from"] }
serde = { version = "1.0.137", features = ["derive"] }
tokio-stream = { version = "0.1.9", features = ["sync"] }
thiserror = "1.0.31"
itertools = "0.10.3"
jsonrpsee = "0.16.2"
jsonrpsee-ws-client = "0.16.2"
finality-grandpa = "0.16.0"
prost = { version = "0.11" }
rand = "0.8.5"

# substrate
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", features = [
	"full_crypto",
] }
ss58-registry = "1.28.0"
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }

# subxt
subxt = { git = "https://github.com/paritytech/subxt", tag = "v0.29.0", features = [
	"substrate-compat",
] }

beefy-primitives = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", package = "sp-consensus-beefy" }
beefy-mmr = { package = "pallet-beefy-mmr", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
pallet-mmr = { package = "pallet-mmr", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
pallet-mmr-primitives = { package = "sp-mmr-primitives", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
transaction-payment-rpc = { package = "pallet-transaction-payment-rpc", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
transaction-payment-runtime-api = { package = "pallet-transaction-payment-rpc-runtime-api", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }

# composable
ibc = { path = "../../ibc/modules", features = [] }
ibc-proto = { path = "../../ibc/proto" }
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs", rev = "e81f7bf23d63ffbcd242381d1ce5e35da3515ff1", default-features = false }
light-client-common = { path = "../../light-clients/common" }
ibc-rpc = { path = "../../contracts/pallet-ibc/rpc" }
pallet-ibc = { path = "../../contracts/pallet-ibc" }
pallet-ibc-ping = { path = "../../contracts/pallet-ibc/ping" }
ibc-primitives = { path = "../../contracts/pallet-ibc/primitives" }

# Beefy
beefy-prover = { path = "../../algorithms/beefy/prover" }
beefy-light-client = { path = "../../algorithms/beefy/verifier" }
beefy-light-client-primitives = { path = "../../algorithms/beefy/primitives" }
ics11-beefy = { path = "../../light-clients/ics11-beefy" }
sc-consensus-beefy-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }

# Grandpa
grandpa-prover = { path = "../../algorithms/grandpa/prover" }
grandpa-light-client-primitives = { path = "../../algorithms/grandpa/primitives" }
ics10-grandpa = { path = "../../light-clients/ics10-grandpa" }
finality-grandpa-rpc = { package = "sc-consensus-grandpa-rpc", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
polkadot-core-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.43" }
sp-consensus-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-weights = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }

[dev-dependencies]
derive_more = "0.99.17"
clap = { version = "3.2.0", features = ["derive"] }
state-machine = { package = "sp-state-machine", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
prost = "0.11"
primitives = { path = "../primitives", package = "hyperspace-primitives", features = [
	"testing",
] }
subxt-generated = { path = "../../utils/subxt/generated" }

[features]
default = ["std"]
testing = ["primitives/testing"]
std = [
	"sp-io/std",
	"frame-support/std",
	"anyhow/std",
	"beefy-light-client/std",
	"beefy-light-client-primitives/std",
	"clap/std",
	"finality-grandpa/std",
	"frame-system/std",
	"futures/std",
	"grandpa-light-client-primitives/std",
	"hex/std",
	"ibc/std",
	"ibc-primitives/std",
	"ibc-proto/std",
	"ics10-grandpa/std",
	"ics11-beefy/std",
	"light-client-common/std",
	"log/std",
	"beefy-mmr/std",
	"pallet-ibc/std",
	"pallet-ibc-ping/std",
	"pallet-mmr/std",
	"transaction-payment-runtime-api/std",
	"codec/std",
	"polkadot-core-primitives/std",
	"prost/std",
	"rand/std",
	"rs_merkle/std",
	"serde/std",
	"serde_json/std",
	"sp-authority-discovery/std",
	"beefy-primitives/std",
	"sp-consensus-grandpa/std",
	"sp-core/std",
	"sp-keystore/std",
	"pallet-mmr-primitives/std",
	"sp-runtime/std",
	"state-machine/std",
	"sp-trie/std",
	"ss58-registry/std",
]
