[package]
name = "grandpa-light-client-verifier"
version = "0.1.0"
edition = "2021"
authors = ["Seun Lanlege <seunlanlege@gmail.com>"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
anyhow = { version = "1.0.64", default-features = false }
finality-grandpa = { version = "0.16.2", features = ["derive-codec"], default-features = false }
hash-db = { version = "0.16.0", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-consensus-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }

primitives = { package = "grandpa-light-client-primitives", path = "../primitives", default-features = false }
light-client-common = { path = "../../../light-clients/common", default-features = false }

[dev-dependencies]
subxt = { git = "https://github.com/paritytech/subxt",  tag = "v0.29.0", features = ["substrate-compat"] }
futures = "0.3.24"
hex = "0.4.3"
serde = "1.0.144"
env_logger = "0.9.0"
log = "0.4.17"
polkadot-core-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.43" }
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
finality-grandpa-rpc = { package = "sc-consensus-grandpa-rpc", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
hex-literal = "0.3.4"
grandpa-prover = { path = "../prover" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
jsonrpsee-ws-client = "0.16.2"
jsonrpsee-core = "0.16.2"
hyperspace-core = { path = "../../../hyperspace/core", features = ["testing", "build-metadata-from-ws"] }
light-client-common = { path = "../../../light-clients/common", features = ["std"] }

[features]
default = ["std"]
std = [
	"codec/std",
	"anyhow/std",
	"finality-grandpa/std",
	"hash-db/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-trie/std",
	"sp-consensus-grandpa/std",
	"sp-state-machine/std",
	"sp-io/std",
	"primitives/std",
	"light-client-common/std",
	"futures/std",
	"hex/std",
	"log/std",
	"polkadot-core-primitives/std",
	"serde/std",
	"sp-core/std"
]
