[package]
name = "codegen"
version = "0.1.0"
edition = "2021"
authors = ["Seun Lanlege <seunlanlege@gmail.com>"]

[[bin]]
name = "codegen"
path = "bin/main.rs"

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
anyhow = "1.0.66"
clap = { version = "3.2.22", features = ["derive", "env"] }
serde_json = "1.0.91"
http = "0.2.9"
subxt-codegen = { git = "https://github.com/paritytech/subxt", tag = "v0.29.0" }
subxt-metadata = { git = "https://github.com/paritytech/subxt", tag = "v0.29.0" }
jsonrpsee = { version = "0.16.2", features = [
    "async-client",
    "client-ws-transport",
    "http-client",
] }
frame-metadata = { version = "15.0.0", features = ["v14", "std"] }
syn = { version = "2.0.15", features = ["full", "extra-traits"] }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
    "derive",
    "max-encoded-len",
] }
hex = "0.4.3"
wasm-testbed = { git = "https://github.com/chevdor/subwasm", rev = "1c8446be5cff9e04cbb7b41acc136f22eddd5eac" }
