name: Slither Analysis

on: [push, pull_request, workflow_dispatch]

jobs:
    analyze:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run Slither
              uses: crytic/slither-action@v0.3.1
              id: slither
              with:
                  node-version: 20
                  fail-on: none
                  slither-args: --filter-paths "@openzeppelin" --exclude-optimization --exclude-informational --exclude-low --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/

            - name: Create/Update checklist as PR comment
              uses: actions/github-script@v7
              if: github.event_name == 'pull_request'
              env:
                  REPORT: ${{ steps.slither.outputs.stdout }}
              with:
                  script: |
                      const script = require('.github/scripts/comment')
                      const header = '# Slither report'
                      const body = process.env.REPORT
                      await script({ github, context, header, body })
