import os
from .globalVar import GCROSSCHAINSENDSIGLIST, GCROSSCHAINRECEIVESIGLIST, GCROSSCHAINRECEIVEEVENTLIST, GCROSSCHAINSENDEVENTLIST,GCROSSCHAINSENDCALLLIST,GCROSSCHAINRECEIVECALLLIST

def get_list(str):
    parts = str.replace(" ", "").split(";")
    filtered_parts = [part for part in parts if part]
    return filtered_parts

def get_args():
    SEND_SIGS = os.environ.get('SEND_FUNCS')
    RECEIVE_SIGS = os.environ.get('RECEIVE_FUNCS')
    SEND_EVENT = os.environ.get('SEND_EVENT')
    RECEIVE_EVENT = os.environ.get('RECEIVE_EVENT')
    SEND_CALL = os.environ.get('SEND_CALL')
    RECEIVE_CALL = os.environ.get('RECEIVE_CALL')

    CROSSCHAINSENDSIGLIST = get_list(SEND_SIGS) if SEND_SIGS else GCROSSCHAINSENDSIGLIST
    CROSSCHAINRECEIVESIGLIST = get_list(RECEIVE_SIGS) if RECEIVE_SIGS else GCROSSCHAINRECEIVESIGLIST
    CROSSCHAINSENDEVENTLIST = get_list(SEND_EVENT) if SEND_EVENT else GCROSSCHAINSENDEVENTLIST
    CROSSCHAINRECEIVEEVENTLIST =  get_list(RECEIVE_EVENT) if RECEIVE_EVENT else GCROSSCHAINRECEIVEEVENTLIST
    CROSSCHAINSENDCALLLIST = get_list(SEND_CALL) if SEND_CALL else GCROSSCHAINSENDCALLLIST
    CROSSCHAINRECEIVECALLLIST = get_list(RECEIVE_CALL) if RECEIVE_CALL else GCROSSCHAINRECEIVECALLLIST

    return CROSSCHAINSENDSIGLIST, CROSSCHAINRECEIVESIGLIST, CROSSCHAINSENDEVENTLIST, CROSSCHAINRECEIVEEVENTLIST, CROSSCHAINSENDCALLLIST, CROSSCHAINRECEIVECALLLIST