[toolchain]
# Note: ahash 0.7.7 and 0.8.6 don’t work with newer nightly versions.
# For the time being sticking to version that works.  Setting this to
# never version will likely require `cargo update -p ahash@0.8.3 &&
# cargo update -p ahash@0.7.6`.
channel = "nightly-2024-02-05"
targets = [ "wasm32-unknown-unknown"]
profile = "minimal"
